adding alert, create and new files
kanzakisuemi/petshop pull request #3
Opened 2023-01-21 19:25 UTC by kanzakisuemi

2023-01-21 20:03 UTC, akirakzk commented on dogs_create.php
> +  header('location:alert.php');
recomendo abrir e fechar tag do php individualmente no "header" e "include" igual foi feito na linha 16

2023-01-21 20:07 UTC, kanzakisuemi commented on dogs_create.php
> +  header('location:alert.php');
thank u bro

2023-01-21 20:19 UTC, akirakzk commented on dogs_new.php
> +    <button class="btn btn-info" type="submit">submit</button>
Sugiro colocar a inicial maiúscula no botão "Submit".

2023-01-21 20:24 UTC, akirakzk commented on dogs_new.php
> +<body>
Recomendo inserir o "head" e o "body" no arquivo "header.php"

2023-01-21 20:25 UTC, akirakzk requested changes, later dismissed
verificar 👀

2023-01-21 20:49 UTC, tbkanzaki reviewed
Tudo ok!!

2023-01-24 13:03 UTC, marcelokanzaki requested changes

2023-01-24 13:03 UTC, marcelokanzaki commented on inc/header.php
> +	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin=
Você incluiu o bootstrap novamente?

2023-01-24 13:03 UTC, marcelokanzaki commented on dogs_create.php
> +  include 'inc/open_dbconn.php'; ?>
Ou você faz assim:
```php
<?php
  header('location:alert.php');
  include 'inc/open_dbconn.php';
?>
```

Ou assim:
```php
<?php header('location:alert.php'); ?>
<?php include 'inc/open_dbconn.php'; ?>
```

2023-01-24 13:13 UTC, kanzakisuemi commented on dogs_create.php
> +  include 'inc/open_dbconn.php'; ?>
🫡

2023-01-24 13:38 UTC, marcelokanzaki requested changes

2023-01-24 13:38 UTC, marcelokanzaki commented on dogs_create.php
> +  $nome =$_POST['nome'];
Use um espaço antes e depois do sinal de igualdade (=)

2023-01-24 13:38 UTC, marcelokanzaki commented on dogs_new.php
> +    <input type="text" class="form-control" name="nome" required><br>
Estruture o seu formulário de acordo com a documentação do bootstrap: https://getbootstrap.com/docs/5.3/forms/form-control/#example

Lá tem vários exemplos.

2023-01-24 21:22 UTC, kanzakisuemi commented on dogs_new.php
> +    <input type="text" class="form-control" name="nome" required><br>
Removi o style que tinha feito e adicionei as divs apresentadas no exemplo.

2023-01-25 22:05 UTC, marcelokanzaki requested changes

2023-01-25 22:05 UTC, marcelokanzaki commented on inc/header.php
> +	<?php include 'navbar.php'; ?>
A navbar é dentro do body, logo antes do container.

2023-01-25 22:05 UTC, marcelokanzaki commented on dogs/new.php
> +<div class="container p-4">
Aqui não precisa do container ele deve ser inserido em todas as páginas pelo header

2023-01-25 22:05 UTC, marcelokanzaki commented on dogs/create.php
> +  header('location:alert.php');
redireciona direto pra index

2023-01-25 22:05 UTC, marcelokanzaki commented on dogs/alert.php
> +<script type="text/javascript">
Remvoer esse arquivo. Depois a gente vai aprender como implementar uma mensagem de confirmação.

2023-01-25 22:33 UTC, merged